---
title: "AirBNBLA"
author: "Sarah Gillespie"
date: "6/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Accessed on `r format(Sys.Date(), "%B %e, %Y")`

<center>

##Ramen Ratings

</center>

```{r StartingItems, message=FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(sf)
library(leaflet)
library(lwgeom)
library(lubridate)
library(RColorBrewer)
library(ggthemes)
```

```{r lookAtTheData, message=FALSE, warning = FALSE}
listings <- read_csv("listings.csv")

smallListingsFULL <- listings %>%
  select(id, name, host_id, neighbourhood, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, availability_365)

smallListings <- listings %>%
  select(id, name, host_id, neighbourhood, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, availability_365)

smallListings <- smallListings %>%
  drop_na()

byNeighborhood <- smallListings %>%
  group_by(neighbourhood)%>%
  summarise(total_reviews = sum(number_of_reviews), mean_price=mean(price), mean_min=mean(minimum_nights), mean_reviews = mean(number_of_reviews))
  

#lets look for a price and number of reviews // number of stays per neighborhood and or mean reviews or total reviews
```


```{r colors, message=FALSE, warning = FALSE}
byNeighborhood$mean_min_groups <- cut(byNeighborhood$mean_min, 
                       breaks = c(-Inf, 1.5, 2.5, 5.5, 13.5, Inf), 
                       labels = c("1 night", "2 nights", "3-5 nights", "6-13 nights", "14+ nights"), 
                       right = FALSE)

#the above groups the mean minimum number of nights into catagories. So If the mean is 2.54 nights than that would be grouped with 3 to 5 nights, but if the mean was 2.3 nights then that would be grouped with 2 nights. This makes the variables go from a continious scale to a discreete scale adn will make my colors look more readable. Source: https://stackoverflow.com/questions/13559076/convert-continuous-numeric-values-to-discrete-categories-defined-by-intervals
                       
```


```{r plotTheData, message=FALSE, warning = FALSE}
plot <- ggplot(byNeighborhood, aes(x = mean_reviews, y = mean_price, color = mean_min_groups)) +
  geom_point()

plot +
  geom_text_repel(data = subset(byNeighborhood, mean_price > 375 | mean_reviews > 90), aes(label = neighbourhood)) +
  theme_hc() +
  ggtitle("Airbnb prices in Los Angeles") +
  labs(y="Average price", x = "Average number of reviews", caption = "By @SarahG4567 Data source: InsideAirbnb.com from 07/08/2019.") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.title=element_blank()) +
  theme(legend.position = c(.93, 0.7)) +
  guides(colour = guide_legend(override.aes = list(size = 3.5))) +
  scale_y_continuous(labels = scales::dollar)

```